# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doubts', '0004_auto_20180108_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
