# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0006_question_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
