# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0008_answers_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(default='others', max_length=500),
        ),
    ]
