# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
