# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='Post',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
