# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180205_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.CharField(max_length=100),
        ),
    ]
