# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-18 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180214_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
