# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-18 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180218_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='by',
        ),
    ]
