# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-04-24 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptertopic',
            name='detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
