# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-04-24 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_chaptertopic_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptertopic',
            name='topic_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
