# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-20 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.PositiveSmallIntegerField(choices=[(1, b'Science'), (2, b'Maths'), (4, b'Chemistry'), (3, b'Physics')])),
                ('standard', models.PositiveSmallIntegerField()),
                ('chapter_no', models.PositiveSmallIntegerField()),
                ('chapter_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=1024)),
                ('notes', models.FileField(max_length=512, upload_to=b'notes')),
                ('topic_name', models.CharField(max_length=1024)),
                ('topic_description', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_material.ChapterDetail')),
            ],
        ),
    ]
