# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-20 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapterdetail',
            unique_together=set([('subject', 'standard', 'chapter_no')]),
        ),
        migrations.AlterUniqueTogether(
            name='studymaterial',
            unique_together=set([('chapter', 'topic_name')]),
        ),
    ]
