# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-14 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_material', '0004_auto_20200614_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousyearpapers',
            name='set_no',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
    ]
