# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-14 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_material', '0005_previousyearpapers_set_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterdetail',
            name='subject',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Science'), (2, b'Maths'), (4, b'Chemistry'), (3, b'Physics'), (5, b'Biology')]),
        ),
        migrations.AlterField(
            model_name='previousyearpapers',
            name='subject',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Science'), (2, b'Maths'), (4, b'Chemistry'), (3, b'Physics'), (5, b'Biology')]),
        ),
    ]
