# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-21 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_material', '0006_auto_20200614_0640'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='previousyearpapers',
            unique_together=set([]),
        ),
    ]
