# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='description',
            new_name='four',
        ),
        migrations.AddField(
            model_name='choices',
            name='one',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choices',
            name='three',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choices',
            name='two',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
