# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20180104_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='right_answer',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
