# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20180105_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='four',
            new_name='option',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='one',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='right_answer',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='three',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='two',
        ),
        migrations.AlterField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Question'),
        ),
    ]
