# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_auto_20180105_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Question')),
            ],
        ),
        migrations.RenameField(
            model_name='choices',
            old_name='option',
            new_name='four',
        ),
        migrations.AddField(
            model_name='choices',
            name='one',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choices',
            name='right_answer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='choices',
            name='three',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choices',
            name='two',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
