# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20180105_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tests.Question'),
        ),
    ]
