# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_auto_20180105_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='your_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tests.Question'),
            preserve_default=False,
        ),
    ]
