# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_auto_20180105_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='your_answer',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
