# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_auto_20180105_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='right_answer',
            new_name='your_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='your_answer',
            new_name='right_answer',
        ),
        migrations.AddField(
            model_name='test',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
