# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_auto_20180105_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='your_answer',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
