# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_auto_20180106_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='number',
        ),
        migrations.RemoveField(
            model_name='test',
            name='score',
        ),
    ]
