# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0023_auto_20180108_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='number',
        ),
    ]
