# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0024_remove_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
