# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0025_question_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num',
        ),
    ]
