# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0026_remove_question_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
