# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0027_question_question_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_no']},
        ),
    ]
