# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0028_auto_20180108_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date_time',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
