# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0029_test_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='date_time',
            new_name='time_limit',
        ),
    ]
