# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0032_score_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='wrong_questions',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
