# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0033_score_wrong_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='owner',
        ),
    ]
