# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0034_remove_test_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='wrong_questions',
        ),
    ]
