# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0036_auto_20180204_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.CharField(default='other', max_length=300),
        ),
    ]
